'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.ISR_ServiceSoap")>  _
    Public Interface ISR_ServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function HelloWorld() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AuthenticateUser", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
        Function AuthenticateUser(ByVal LoginName As String, ByVal Password As String) As System.Data.DataTable

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetAppUsers", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
        Function GetAppUsers() As System.Data.DataTable

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetQueryType", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
        Function GetQueryType(ByVal QueryMainTypeID As Integer) As System.Data.DataTable

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetMainQueryType", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
        Function GetMainQueryType() As System.Data.DataTable

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetRecivedFrom", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
        Function GetRecivedFrom() As System.Data.DataTable

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetStatus", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
        Function GetStatus() As System.Data.DataTable

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetComplainMode", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
        Function GetComplainMode() As System.Data.DataTable

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InsertIncident", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
        Function InsertIncident(ByVal IncidentID As Integer, ByVal StartDateTime As Date, ByVal ComplainModeID As Integer, ByVal QueryTypeID As Integer, ByVal Category As String, ByVal Initiator As String, ByVal RecivedFromID As Integer, ByVal StatusID As Integer, ByVal ClosedByID As Integer, ByVal CloseDateTime As Date, ByVal Aging As String, ByVal Remarks As String, ByVal TransactionBy As Integer, ByVal TransactionDateTime As Date) As Integer

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncidentReport", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
        Function GetIncidentReport(ByVal ClosedByID As Integer, ByVal ComplainModeID As Integer, ByVal QueryTypeID As Integer, ByVal RecivedFromID As Integer, ByVal StatusID As Integer, ByVal CloseDateTimeFrom As Date, ByVal CloseDateTimeTO As Date) As System.Data.DataTable

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIncidentDetailByIncidentID", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
        Function GetIncidentDetailByIncidentID(ByVal IncidentID As Integer) As System.Data.DataTable

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateIncident", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
        Function UpdateIncident(ByVal IncidentID As Integer, ByVal StartDateTime As Date, ByVal ComplainModeID As Integer, ByVal QueryTypeID As Integer, ByVal Category As String, ByVal Initiator As String, ByVal RecivedFromID As Integer, ByVal StatusID As Integer, ByVal ClosedByID As Integer, ByVal CloseDateTime As Date, ByVal Aging As String, ByVal Remarks As String, ByVal TransactionBy As Integer, ByVal TransactionDateTime As Date) As Integer

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetRemarksHistoryByIncidentID", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=True)> _
        Function GetRemarksHistoryByIncidentID(ByVal IncidentID As Integer) As System.Data.DataTable
    End Interface

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
    Public Interface ISR_ServiceSoapChannel
        Inherits ServiceReference1.ISR_ServiceSoap, System.ServiceModel.IClientChannel
    End Interface

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
    Partial Public Class SR_ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.ISR_ServiceSoap)
        Implements ServiceReference1.ISR_ServiceSoap

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub

        Public Function HelloWorld() As String Implements ServiceReference1.ISR_ServiceSoap.HelloWorld
            Return MyBase.Channel.HelloWorld
        End Function

        Public Function AuthenticateUser(ByVal LoginName As String, ByVal Password As String) As System.Data.DataTable Implements ServiceReference1.ISR_ServiceSoap.AuthenticateUser
            Return MyBase.Channel.AuthenticateUser(LoginName, Password)
        End Function
        
        Public Function GetAppUsers() As System.Data.DataTable Implements ServiceReference1.ISR_ServiceSoap.GetAppUsers
            Return MyBase.Channel.GetAppUsers
        End Function
        
        Public Function GetQueryType(ByVal QueryMainTypeID As Integer) As System.Data.DataTable Implements ServiceReference1.ISR_ServiceSoap.GetQueryType
            Return MyBase.Channel.GetQueryType(QueryMainTypeID)
        End Function
        
        Public Function GetMainQueryType() As System.Data.DataTable Implements ServiceReference1.ISR_ServiceSoap.GetMainQueryType
            Return MyBase.Channel.GetMainQueryType
        End Function
        
        Public Function GetRecivedFrom() As System.Data.DataTable Implements ServiceReference1.ISR_ServiceSoap.GetRecivedFrom
            Return MyBase.Channel.GetRecivedFrom
        End Function
        
        Public Function GetStatus() As System.Data.DataTable Implements ServiceReference1.ISR_ServiceSoap.GetStatus
            Return MyBase.Channel.GetStatus
        End Function
        
        Public Function GetComplainMode() As System.Data.DataTable Implements ServiceReference1.ISR_ServiceSoap.GetComplainMode
            Return MyBase.Channel.GetComplainMode
        End Function
        
        Public Function InsertIncident(ByVal IncidentID As Integer, ByVal StartDateTime As Date, ByVal ComplainModeID As Integer, ByVal QueryTypeID As Integer, ByVal Category As String, ByVal Initiator As String, ByVal RecivedFromID As Integer, ByVal StatusID As Integer, ByVal ClosedByID As Integer, ByVal CloseDateTime As Date, ByVal Aging As String, ByVal Remarks As String, ByVal TransactionBy As Integer, ByVal TransactionDateTime As Date) As Integer Implements ServiceReference1.ISR_ServiceSoap.InsertIncident
            Return MyBase.Channel.InsertIncident(IncidentID, StartDateTime, ComplainModeID, QueryTypeID, Category, Initiator, RecivedFromID, StatusID, ClosedByID, CloseDateTime, Aging, Remarks, TransactionBy, TransactionDateTime)
        End Function
        
        Public Function GetIncidentReport(ByVal ClosedByID As Integer, ByVal ComplainModeID As Integer, ByVal QueryTypeID As Integer, ByVal RecivedFromID As Integer, ByVal StatusID As Integer, ByVal CloseDateTimeFrom As Date, ByVal CloseDateTimeTO As Date) As System.Data.DataTable Implements ServiceReference1.ISR_ServiceSoap.GetIncidentReport
            Return MyBase.Channel.GetIncidentReport(ClosedByID, ComplainModeID, QueryTypeID, RecivedFromID, StatusID, CloseDateTimeFrom, CloseDateTimeTO)
        End Function
        
        Public Function GetIncidentDetailByIncidentID(ByVal IncidentID As Integer) As System.Data.DataTable Implements ServiceReference1.ISR_ServiceSoap.GetIncidentDetailByIncidentID
            Return MyBase.Channel.GetIncidentDetailByIncidentID(IncidentID)
        End Function
        
        Public Function UpdateIncident(ByVal IncidentID As Integer, ByVal StartDateTime As Date, ByVal ComplainModeID As Integer, ByVal QueryTypeID As Integer, ByVal Category As String, ByVal Initiator As String, ByVal RecivedFromID As Integer, ByVal StatusID As Integer, ByVal ClosedByID As Integer, ByVal CloseDateTime As Date, ByVal Aging As String, ByVal Remarks As String, ByVal TransactionBy As Integer, ByVal TransactionDateTime As Date) As Integer Implements ServiceReference1.ISR_ServiceSoap.UpdateIncident
            Return MyBase.Channel.UpdateIncident(IncidentID, StartDateTime, ComplainModeID, QueryTypeID, Category, Initiator, RecivedFromID, StatusID, ClosedByID, CloseDateTime, Aging, Remarks, TransactionBy, TransactionDateTime)
        End Function
        
        Public Function GetRemarksHistoryByIncidentID(ByVal IncidentID As Integer) As System.Data.DataTable Implements ServiceReference1.ISR_ServiceSoap.GetRemarksHistoryByIncidentID
            Return MyBase.Channel.GetRemarksHistoryByIncidentID(IncidentID)
        End Function
    End Class
End Namespace
